### ISSUE TITLE
Demo link to disk image returns 404

### ISSUE THREAD

**Issue by speich** [humphd/nohost#3]
When using the link to the demo disk image nothing happens (FF 39 Beta). Developer console reveals:
UnknownError filer.min.js:2:0
ReferenceError: EFileSystemError is not defined filer.min.js:6:6506
and the network console reports a 404 for http://humphd.github.io/nohost/webmaker-kits-gh-pages.zip

**Comment by humphd** [comment]
I've refactored this into a service worker, closing as this is no longer relevant.
